### PR TITLE
Update Localization Structure to Kodi v.19 Matrix

### PR DESCRIPTION
**Pull request by arustler**
Updated Localization Structure to Kodi v.19 Matrix [Language support - Official Kodi Wiki](https://kodi.wiki/view/Language_support)
Update string formatting to comply to python version >2.7 [PyFormat: Using % and .format() for great good!](https://pyformat.info/)

### CODE REVIEW

**Comment by RobLoach** [comment]
This is incredible! Thank you so much for pushing this up.

**Comment by arustler** [comment]
I just saw there were some changes I didn't catch updating my fork.
Please check in default.py
- line 23
- line 47
- line 147

**Comment by RobLoach** [comment]
Seems to be working here. Is there some changes missing?

**Comment by arustler** [comment]
I’ve forgot to include @solbero commits. Let me include them before merging the PR

**Comment by solbero** [comment]
Looks good, I'll test it tomorrow on my setup.

**Comment by solbero** [comment]
I didn't find any bug, so I think this can be safely merged.

**Pull request merged**
