### PR TITLE
Fixed format error due to extra lutris logs

### PR DESCRIPTION
**Pull request by Turpster**
#47

### CODE REVIEW

**Comment by solbero** [comment]
Looking at you code it seems like your suggested change trims the last line from the JSON output. Is this correct?

**Comment by Turpster** [comment]
It's a rough fix, currently works because I don't know of any brackets that could end up inside the json

**Comment by solbero** [comment]
I am hesitant to merge this PR. I would like a solution that validated the JSON and discarded the garbage before converting to a Python array. I think that your change could introduce new problems later.

However, my preferred fix is for Lutris to only output valid JSON when requested.

**Comment by solbero** [comment]
I finally had the time to look some more at your proposed fix. Looking at it again it does solve the log problem quite nicely. The fix assumes that the log message appears outside the square brackets of the JSON. After some thought this assumption seems fine, since if the log message appeared inside the JSON brackets then `json.load()`  would thill complained about malformed JSON input.

There has not been any response to your issue at the Lutris repo, so I will merge this to solve your problem if it passes some testing on my system later today.

**Comment by solbero** [comment]
The problem with Lutris outputting an error message in the JSON output is fixed upstream. Here is the commit that fixes it: https://github.com/lutris/lutris/commit/fe01f93f85371e105fa288187e974294f2fab377

**Pull request merged**
